// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // ignore_for_file: type=lint,unused_import

// GENERATED BY drift_dev, DO NOT MODIFY.
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    wallets,
    parties,
    groups,
    transactions,
    categories,
    configs,
    users,
    localChanges,
    syncMetadata,
    categorizables,
    notifications,
  ];
  late final Shape0 wallets = Shape0(
      source: i0.VersionedTable(
        entityName: 'wallets',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_8,
          _column_9,
          _column_10,
          _column_11,
          _column_12,
          _column_13,
          _column_14,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 parties = Shape1(
      source: i0.VersionedTable(
        entityName: 'parties',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_8,
          _column_12,
          _column_14,
          _column_15,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape2 groups = Shape2(
      source: i0.VersionedTable(
        entityName: 'groups',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_8,
          _column_12,
          _column_14,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape3 transactions = Shape3(
      source: i0.VersionedTable(
        entityName: 'transactions',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_16,
          _column_9,
          _column_12,
          _column_17,
          _column_18,
          _column_19,
          _column_20,
          _column_21,
          _column_22,
          _column_23,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape4 categories = Shape4(
      source: i0.VersionedTable(
        entityName: 'categories',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_24,
          _column_25,
          _column_12,
          _column_9,
          _column_14,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape5 configs = Shape5(
      source: i0.VersionedTable(
        entityName: 'configs',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_26,
          _column_9,
          _column_27,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape6 users = Shape6(
      source: i0.VersionedTable(
        entityName: 'users',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_28,
          _column_29,
          _column_30,
          _column_31,
          _column_32,
          _column_33,
          _column_34,
          _column_35,
          _column_36,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape7 localChanges = Shape7(
      source: i0.VersionedTable(
        entityName: 'local_changes',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(entity_id, entity_type)',
        ],
        columns: [
          _column_37,
          _column_38,
          _column_39,
          _column_40,
          _column_41,
          _column_42,
          _column_43,
          _column_44,
          _column_45,
          _column_46,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape8 syncMetadata = Shape8(
      source: i0.VersionedTable(
        entityName: 'sync_metadata',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(entity_type)',
        ],
        columns: [
          _column_37,
          _column_7,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape9 categorizables = Shape9(
      source: i0.VersionedTable(
        entityName: 'categorizables',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(categorizable_id, categorizable_type, category_client_id)',
        ],
        columns: [
          _column_47,
          _column_48,
          _column_49,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape10 notifications = Shape10(
      source: i0.VersionedTable(
        entityName: 'notifications',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_9,
          _column_50,
          _column_51,
          _column_41,
          _column_52,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get clientId =>
      columnsByName['client_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get rev =>
      columnsByName['rev']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get lastSyncedAt =>
      columnsByName['last_synced_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get balance =>
      columnsByName['balance']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get currency =>
      columnsByName['currency']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get stats =>
      columnsByName['stats']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get icon =>
      columnsByName['icon']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>('id', aliasedName, true,
        type: i1.DriftSqlType.int,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways('UNIQUE'));
i1.GeneratedColumn<int> _column_1(String aliasedName) =>
    i1.GeneratedColumn<int>('user_id', aliasedName, true,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>('client_id', aliasedName, false,
        type: i1.DriftSqlType.string,
        defaultValue: const CustomExpression('\'\''));
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>('rev', aliasedName, true,
        type: i1.DriftSqlType.string,
        defaultValue: const CustomExpression('\'1\''));
i1.GeneratedColumn<DateTime> _column_4(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('created_at', aliasedName, false,
        type: i1.DriftSqlType.dateTime,
        defaultValue: const CustomExpression('CURRENT_TIMESTAMP'));
i1.GeneratedColumn<DateTime> _column_5(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('updated_at', aliasedName, false,
        type: i1.DriftSqlType.dateTime,
        defaultValue: const CustomExpression('CURRENT_TIMESTAMP'));
i1.GeneratedColumn<DateTime> _column_6(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('deleted_at', aliasedName, true,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<DateTime> _column_7(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('last_synced_at', aliasedName, true,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>('name', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>('type', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<double> _column_10(String aliasedName) =>
    i1.GeneratedColumn<double>('balance', aliasedName, false,
        type: i1.DriftSqlType.double,
        defaultValue: const CustomExpression('0.0'));
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>('currency', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>('description', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>('stats', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>('icon', aliasedName, true,
        type: i1.DriftSqlType.string);

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get clientId =>
      columnsByName['client_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get rev =>
      columnsByName['rev']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get lastSyncedAt =>
      columnsByName['last_synced_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get icon =>
      columnsByName['icon']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>('type', aliasedName, true,
        type: i1.DriftSqlType.string);

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get clientId =>
      columnsByName['client_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get rev =>
      columnsByName['rev']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get lastSyncedAt =>
      columnsByName['last_synced_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get icon =>
      columnsByName['icon']! as i1.GeneratedColumn<String>;
}

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get clientId =>
      columnsByName['client_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get rev =>
      columnsByName['rev']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get lastSyncedAt =>
      columnsByName['last_synced_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<double> get amount =>
      columnsByName['amount']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get datetime =>
      columnsByName['datetime']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<int> get partyId =>
      columnsByName['party_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get walletId =>
      columnsByName['wallet_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get groupId =>
      columnsByName['group_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get walletClientId =>
      columnsByName['wallet_client_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get partyClientId =>
      columnsByName['party_client_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get groupClientId =>
      columnsByName['group_client_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<double> _column_16(String aliasedName) =>
    i1.GeneratedColumn<double>('amount', aliasedName, false,
        type: i1.DriftSqlType.double);
i1.GeneratedColumn<DateTime> _column_17(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('datetime', aliasedName, true,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>('party_id', aliasedName, true,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<int> _column_19(String aliasedName) =>
    i1.GeneratedColumn<int>('wallet_id', aliasedName, true,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>('group_id', aliasedName, true,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>('wallet_client_id', aliasedName, false,
        type: i1.DriftSqlType.string,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'REFERENCES wallets (client_id)'));
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>('party_client_id', aliasedName, true,
        type: i1.DriftSqlType.string,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'REFERENCES parties (client_id)'));
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>('group_client_id', aliasedName, true,
        type: i1.DriftSqlType.string,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'REFERENCES "groups" (client_id)'));

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get clientId =>
      columnsByName['client_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get rev =>
      columnsByName['rev']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get lastSyncedAt =>
      columnsByName['last_synced_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get slug =>
      columnsByName['slug']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get icon =>
      columnsByName['icon']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>('name', aliasedName, false,
        type: i1.DriftSqlType.string,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways('UNIQUE'));
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>('slug', aliasedName, false,
        type: i1.DriftSqlType.string);

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get clientId =>
      columnsByName['client_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get rev =>
      columnsByName['rev']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get lastSyncedAt =>
      columnsByName['last_synced_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>('key', aliasedName, false,
        type: i1.DriftSqlType.string,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways('UNIQUE'));
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>('value', aliasedName, false,
        type: i1.DriftSqlType.string);

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get email =>
      columnsByName['email']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get firstName =>
      columnsByName['first_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastName =>
      columnsByName['last_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get username =>
      columnsByName['username']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get phone =>
      columnsByName['phone']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get avatar =>
      columnsByName['avatar']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>('id', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>('email', aliasedName, false,
        type: i1.DriftSqlType.string,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways('UNIQUE'));
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>('first_name', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>('last_name', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>('username', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>('phone', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>('avatar', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<DateTime> _column_35(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('created_at', aliasedName, true,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<DateTime> _column_36(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('updated_at', aliasedName, true,
        type: i1.DriftSqlType.dateTime);

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get entityType =>
      columnsByName['entity_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get entityId =>
      columnsByName['entity_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get entityRev =>
      columnsByName['entity_rev']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get deleted =>
      columnsByName['deleted']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<String> get data =>
      columnsByName['data']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createAt =>
      columnsByName['create_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<bool> get concluded =>
      columnsByName['concluded']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<DateTime> get concludedMoment =>
      columnsByName['concluded_moment']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get error =>
      columnsByName['error']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get dismissed =>
      columnsByName['dismissed']! as i1.GeneratedColumn<bool>;
}

i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>('entity_type', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>('entity_id', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_39(String aliasedName) =>
    i1.GeneratedColumn<String>('entity_rev', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<bool> _column_40(String aliasedName) =>
    i1.GeneratedColumn<bool>('deleted', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("deleted" IN (0, 1))'));
i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>('data', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<DateTime> _column_42(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('create_at', aliasedName, false,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<bool> _column_43(String aliasedName) =>
    i1.GeneratedColumn<bool>('concluded', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("concluded" IN (0, 1))'));
i1.GeneratedColumn<DateTime> _column_44(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('concluded_moment', aliasedName, true,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>('error', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<bool> _column_46(String aliasedName) =>
    i1.GeneratedColumn<bool>('dismissed', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("dismissed" IN (0, 1))'));

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get entityType =>
      columnsByName['entity_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get lastSyncedAt =>
      columnsByName['last_synced_at']! as i1.GeneratedColumn<DateTime>;
}

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get categorizableId =>
      columnsByName['categorizable_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get categorizableType =>
      columnsByName['categorizable_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get categoryClientId =>
      columnsByName['category_client_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>('categorizable_id', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_48(String aliasedName) =>
    i1.GeneratedColumn<String>('categorizable_type', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_49(String aliasedName) =>
    i1.GeneratedColumn<String>('category_client_id', aliasedName, false,
        type: i1.DriftSqlType.string,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'REFERENCES categories (client_id)'));

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get clientId =>
      columnsByName['client_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get rev =>
      columnsByName['rev']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get lastSyncedAt =>
      columnsByName['last_synced_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get body =>
      columnsByName['body']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get data =>
      columnsByName['data']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get readAt =>
      columnsByName['read_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>('title', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>('body', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<DateTime> _column_52(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('read_at', aliasedName, true,
        type: i1.DriftSqlType.dateTime);

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    wallets,
    parties,
    groups,
    transactions,
    categories,
    configs,
    users,
    localChanges,
    syncMetadata,
    categorizables,
    notifications,
    mediaFiles,
  ];
  late final Shape0 wallets = Shape0(
      source: i0.VersionedTable(
        entityName: 'wallets',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_8,
          _column_9,
          _column_10,
          _column_11,
          _column_12,
          _column_13,
          _column_14,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 parties = Shape1(
      source: i0.VersionedTable(
        entityName: 'parties',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_8,
          _column_12,
          _column_14,
          _column_15,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape2 groups = Shape2(
      source: i0.VersionedTable(
        entityName: 'groups',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_8,
          _column_12,
          _column_14,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape3 transactions = Shape3(
      source: i0.VersionedTable(
        entityName: 'transactions',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_16,
          _column_9,
          _column_12,
          _column_17,
          _column_18,
          _column_19,
          _column_20,
          _column_21,
          _column_22,
          _column_23,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape4 categories = Shape4(
      source: i0.VersionedTable(
        entityName: 'categories',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_24,
          _column_25,
          _column_12,
          _column_9,
          _column_14,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape5 configs = Shape5(
      source: i0.VersionedTable(
        entityName: 'configs',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_26,
          _column_9,
          _column_27,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape6 users = Shape6(
      source: i0.VersionedTable(
        entityName: 'users',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_28,
          _column_29,
          _column_30,
          _column_31,
          _column_32,
          _column_33,
          _column_34,
          _column_35,
          _column_36,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape7 localChanges = Shape7(
      source: i0.VersionedTable(
        entityName: 'local_changes',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(entity_id, entity_type)',
        ],
        columns: [
          _column_37,
          _column_38,
          _column_39,
          _column_40,
          _column_41,
          _column_42,
          _column_43,
          _column_44,
          _column_45,
          _column_46,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape8 syncMetadata = Shape8(
      source: i0.VersionedTable(
        entityName: 'sync_metadata',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(entity_type)',
        ],
        columns: [
          _column_37,
          _column_7,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape9 categorizables = Shape9(
      source: i0.VersionedTable(
        entityName: 'categorizables',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(categorizable_id, categorizable_type, category_client_id)',
        ],
        columns: [
          _column_47,
          _column_48,
          _column_49,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape10 notifications = Shape10(
      source: i0.VersionedTable(
        entityName: 'notifications',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_9,
          _column_50,
          _column_51,
          _column_41,
          _column_52,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape11 mediaFiles = Shape11(
      source: i0.VersionedTable(
        entityName: 'media_files',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(path)',
        ],
        columns: [
          _column_53,
          _column_54,
          _column_15,
          _column_55,
          _column_56,
          _column_57,
          _column_58,
          _column_35,
          _column_36,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get path =>
      columnsByName['path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get fileableType =>
      columnsByName['fileable_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get fileableId =>
      columnsByName['fileable_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get localFileableType =>
      columnsByName['local_fileable_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get localFileableId =>
      columnsByName['local_fileable_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_53(String aliasedName) =>
    i1.GeneratedColumn<String>('path', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<int> _column_54(String aliasedName) =>
    i1.GeneratedColumn<int>('id', aliasedName, true, type: i1.DriftSqlType.int);
i1.GeneratedColumn<String> _column_55(String aliasedName) =>
    i1.GeneratedColumn<String>('fileable_type', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<int> _column_56(String aliasedName) =>
    i1.GeneratedColumn<int>('fileable_id', aliasedName, true,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<String> _column_57(String aliasedName) =>
    i1.GeneratedColumn<String>('local_fileable_type', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_58(String aliasedName) =>
    i1.GeneratedColumn<String>('local_fileable_id', aliasedName, true,
        type: i1.DriftSqlType.string);

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    wallets,
    parties,
    groups,
    transactions,
    categories,
    configs,
    users,
    localChanges,
    syncMetadata,
    categorizables,
    notifications,
    mediaFiles,
    transfers,
  ];
  late final Shape0 wallets = Shape0(
      source: i0.VersionedTable(
        entityName: 'wallets',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_8,
          _column_9,
          _column_10,
          _column_11,
          _column_12,
          _column_13,
          _column_14,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 parties = Shape1(
      source: i0.VersionedTable(
        entityName: 'parties',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_8,
          _column_12,
          _column_14,
          _column_15,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape2 groups = Shape2(
      source: i0.VersionedTable(
        entityName: 'groups',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_8,
          _column_12,
          _column_14,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape12 transactions = Shape12(
      source: i0.VersionedTable(
        entityName: 'transactions',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_16,
          _column_9,
          _column_12,
          _column_17,
          _column_18,
          _column_19,
          _column_20,
          _column_21,
          _column_22,
          _column_23,
          _column_59,
          _column_60,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape4 categories = Shape4(
      source: i0.VersionedTable(
        entityName: 'categories',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_24,
          _column_25,
          _column_12,
          _column_9,
          _column_14,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape5 configs = Shape5(
      source: i0.VersionedTable(
        entityName: 'configs',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_26,
          _column_9,
          _column_27,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape6 users = Shape6(
      source: i0.VersionedTable(
        entityName: 'users',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_28,
          _column_29,
          _column_30,
          _column_31,
          _column_32,
          _column_33,
          _column_34,
          _column_35,
          _column_36,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape7 localChanges = Shape7(
      source: i0.VersionedTable(
        entityName: 'local_changes',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(entity_id, entity_type)',
        ],
        columns: [
          _column_37,
          _column_38,
          _column_39,
          _column_40,
          _column_41,
          _column_42,
          _column_43,
          _column_44,
          _column_45,
          _column_46,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape8 syncMetadata = Shape8(
      source: i0.VersionedTable(
        entityName: 'sync_metadata',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(entity_type)',
        ],
        columns: [
          _column_37,
          _column_7,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape9 categorizables = Shape9(
      source: i0.VersionedTable(
        entityName: 'categorizables',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(categorizable_id, categorizable_type, category_client_id)',
        ],
        columns: [
          _column_47,
          _column_48,
          _column_49,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape10 notifications = Shape10(
      source: i0.VersionedTable(
        entityName: 'notifications',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_9,
          _column_50,
          _column_51,
          _column_41,
          _column_52,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape11 mediaFiles = Shape11(
      source: i0.VersionedTable(
        entityName: 'media_files',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(path)',
        ],
        columns: [
          _column_53,
          _column_54,
          _column_15,
          _column_55,
          _column_56,
          _column_57,
          _column_58,
          _column_35,
          _column_36,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape13 transfers = Shape13(
      source: i0.VersionedTable(
        entityName: 'transfers',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_16,
          _column_61,
          _column_62,
          _column_63,
          _column_64,
          _column_65,
          _column_66,
          _column_67,
          _column_68,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get clientId =>
      columnsByName['client_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get rev =>
      columnsByName['rev']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get lastSyncedAt =>
      columnsByName['last_synced_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<double> get amount =>
      columnsByName['amount']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get datetime =>
      columnsByName['datetime']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<int> get partyId =>
      columnsByName['party_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get walletId =>
      columnsByName['wallet_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get groupId =>
      columnsByName['group_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get walletClientId =>
      columnsByName['wallet_client_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get partyClientId =>
      columnsByName['party_client_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get groupClientId =>
      columnsByName['group_client_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get transferId =>
      columnsByName['transfer_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get transferClientId =>
      columnsByName['transfer_client_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_59(String aliasedName) =>
    i1.GeneratedColumn<int>('transfer_id', aliasedName, true,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<String> _column_60(String aliasedName) =>
    i1.GeneratedColumn<String>('transfer_client_id', aliasedName, true,
        type: i1.DriftSqlType.string);

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get clientId =>
      columnsByName['client_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get rev =>
      columnsByName['rev']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get lastSyncedAt =>
      columnsByName['last_synced_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<double> get amount =>
      columnsByName['amount']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get fromWalletId =>
      columnsByName['from_wallet_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get toWalletId =>
      columnsByName['to_wallet_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get fromWalletClientId =>
      columnsByName['from_wallet_client_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get toWalletClientId =>
      columnsByName['to_wallet_client_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get exchangeRate =>
      columnsByName['exchange_rate']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<DateTime> get datetime =>
      columnsByName['datetime']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get expenseTransactionClientId =>
      columnsByName['expense_transaction_client_id']!
          as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get incomeTransactionClientId =>
      columnsByName['income_transaction_client_id']!
          as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_61(String aliasedName) =>
    i1.GeneratedColumn<int>('from_wallet_id', aliasedName, true,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<int> _column_62(String aliasedName) =>
    i1.GeneratedColumn<int>('to_wallet_id', aliasedName, true,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<String> _column_63(String aliasedName) =>
    i1.GeneratedColumn<String>('from_wallet_client_id', aliasedName, true,
        type: i1.DriftSqlType.string,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'REFERENCES wallets (client_id)'));
i1.GeneratedColumn<String> _column_64(String aliasedName) =>
    i1.GeneratedColumn<String>('to_wallet_client_id', aliasedName, true,
        type: i1.DriftSqlType.string,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'REFERENCES wallets (client_id)'));
i1.GeneratedColumn<double> _column_65(String aliasedName) =>
    i1.GeneratedColumn<double>('exchange_rate', aliasedName, true,
        type: i1.DriftSqlType.double);
i1.GeneratedColumn<DateTime> _column_66(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('datetime', aliasedName, false,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<String> _column_67(String aliasedName) =>
    i1.GeneratedColumn<String>(
        'expense_transaction_client_id', aliasedName, true,
        type: i1.DriftSqlType.string,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'REFERENCES transactions (client_id)'));
i1.GeneratedColumn<String> _column_68(String aliasedName) =>
    i1.GeneratedColumn<String>(
        'income_transaction_client_id', aliasedName, true,
        type: i1.DriftSqlType.string,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'REFERENCES transactions (client_id)'));

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    wallets,
    parties,
    groups,
    transactions,
    categories,
    configs,
    users,
    localChanges,
    syncMetadata,
    categorizables,
    notifications,
    mediaFiles,
    transfers,
    budgets,
    budgetTargets,
    budgetPeriodStates,
  ];
  late final Shape0 wallets = Shape0(
      source: i0.VersionedTable(
        entityName: 'wallets',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_8,
          _column_9,
          _column_10,
          _column_11,
          _column_12,
          _column_13,
          _column_14,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 parties = Shape1(
      source: i0.VersionedTable(
        entityName: 'parties',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_8,
          _column_12,
          _column_14,
          _column_15,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape2 groups = Shape2(
      source: i0.VersionedTable(
        entityName: 'groups',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_8,
          _column_12,
          _column_14,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape12 transactions = Shape12(
      source: i0.VersionedTable(
        entityName: 'transactions',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_16,
          _column_9,
          _column_12,
          _column_17,
          _column_18,
          _column_19,
          _column_20,
          _column_21,
          _column_22,
          _column_23,
          _column_59,
          _column_60,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape4 categories = Shape4(
      source: i0.VersionedTable(
        entityName: 'categories',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_24,
          _column_25,
          _column_12,
          _column_9,
          _column_14,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape5 configs = Shape5(
      source: i0.VersionedTable(
        entityName: 'configs',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_26,
          _column_9,
          _column_27,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape6 users = Shape6(
      source: i0.VersionedTable(
        entityName: 'users',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_28,
          _column_29,
          _column_30,
          _column_31,
          _column_32,
          _column_33,
          _column_34,
          _column_35,
          _column_36,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape7 localChanges = Shape7(
      source: i0.VersionedTable(
        entityName: 'local_changes',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(entity_id, entity_type)',
        ],
        columns: [
          _column_37,
          _column_38,
          _column_39,
          _column_40,
          _column_41,
          _column_42,
          _column_43,
          _column_44,
          _column_45,
          _column_46,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape8 syncMetadata = Shape8(
      source: i0.VersionedTable(
        entityName: 'sync_metadata',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(entity_type)',
        ],
        columns: [
          _column_37,
          _column_7,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape9 categorizables = Shape9(
      source: i0.VersionedTable(
        entityName: 'categorizables',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(categorizable_id, categorizable_type, category_client_id)',
        ],
        columns: [
          _column_47,
          _column_48,
          _column_49,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape10 notifications = Shape10(
      source: i0.VersionedTable(
        entityName: 'notifications',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_9,
          _column_50,
          _column_51,
          _column_41,
          _column_52,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape11 mediaFiles = Shape11(
      source: i0.VersionedTable(
        entityName: 'media_files',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(path)',
        ],
        columns: [
          _column_53,
          _column_54,
          _column_15,
          _column_55,
          _column_56,
          _column_57,
          _column_58,
          _column_35,
          _column_36,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape13 transfers = Shape13(
      source: i0.VersionedTable(
        entityName: 'transfers',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_16,
          _column_61,
          _column_62,
          _column_63,
          _column_64,
          _column_65,
          _column_66,
          _column_67,
          _column_68,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape14 budgets = Shape14(
      source: i0.VersionedTable(
        entityName: 'budgets',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_8,
          _column_25,
          _column_12,
          _column_69,
          _column_11,
          _column_70,
          _column_71,
          _column_72,
          _column_73,
          _column_74,
          _column_75,
          _column_76,
          _column_77,
          _column_78,
          _column_79,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape15 budgetTargets = Shape15(
      source: i0.VersionedTable(
        entityName: 'budget_targets',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(budget_client_id, target_type, target_client_id)',
        ],
        columns: [
          _column_80,
          _column_81,
          _column_82,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape16 budgetPeriodStates = Shape16(
      source: i0.VersionedTable(
        entityName: 'budget_period_states',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_80,
          _column_83,
          _column_84,
          _column_85,
          _column_86,
          _column_87,
          _column_88,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

class Shape14 extends i0.VersionedTable {
  Shape14({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get clientId =>
      columnsByName['client_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get rev =>
      columnsByName['rev']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get lastSyncedAt =>
      columnsByName['last_synced_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get slug =>
      columnsByName['slug']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get amount =>
      columnsByName['amount']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get currency =>
      columnsByName['currency']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get periodType =>
      columnsByName['period_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get startDate =>
      columnsByName['start_date']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get endDate =>
      columnsByName['end_date']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<bool> get rolloverEnabled =>
      columnsByName['rollover_enabled']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<int> get thresholdPercent =>
      columnsByName['threshold_percent']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<bool> get forecastAlertsEnabled =>
      columnsByName['forecast_alerts_enabled']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get isActive =>
      columnsByName['is_active']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<String> get ownerType =>
      columnsByName['owner_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get ownerId =>
      columnsByName['owner_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get progress =>
      columnsByName['progress']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_69(String aliasedName) =>
    i1.GeneratedColumn<String>('amount', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_70(String aliasedName) =>
    i1.GeneratedColumn<String>('period_type', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<DateTime> _column_71(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('start_date', aliasedName, false,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<DateTime> _column_72(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('end_date', aliasedName, true,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<bool> _column_73(String aliasedName) =>
    i1.GeneratedColumn<bool>('rollover_enabled', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("rollover_enabled" IN (0, 1))'),
        defaultValue: const CustomExpression('0'));
i1.GeneratedColumn<int> _column_74(String aliasedName) =>
    i1.GeneratedColumn<int>('threshold_percent', aliasedName, false,
        type: i1.DriftSqlType.int, defaultValue: const CustomExpression('80'));
i1.GeneratedColumn<bool> _column_75(String aliasedName) =>
    i1.GeneratedColumn<bool>('forecast_alerts_enabled', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("forecast_alerts_enabled" IN (0, 1))'),
        defaultValue: const CustomExpression('0'));
i1.GeneratedColumn<bool> _column_76(String aliasedName) =>
    i1.GeneratedColumn<bool>('is_active', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("is_active" IN (0, 1))'),
        defaultValue: const CustomExpression('1'));
i1.GeneratedColumn<String> _column_77(String aliasedName) =>
    i1.GeneratedColumn<String>('owner_type', aliasedName, false,
        type: i1.DriftSqlType.string,
        defaultValue: const CustomExpression('\'user\''));
i1.GeneratedColumn<int> _column_78(String aliasedName) =>
    i1.GeneratedColumn<int>('owner_id', aliasedName, true,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<String> _column_79(String aliasedName) =>
    i1.GeneratedColumn<String>('progress', aliasedName, true,
        type: i1.DriftSqlType.string);

class Shape15 extends i0.VersionedTable {
  Shape15({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get budgetClientId =>
      columnsByName['budget_client_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get targetType =>
      columnsByName['target_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get targetClientId =>
      columnsByName['target_client_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_80(String aliasedName) =>
    i1.GeneratedColumn<String>('budget_client_id', aliasedName, false,
        type: i1.DriftSqlType.string,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'REFERENCES budgets (client_id)'));
i1.GeneratedColumn<String> _column_81(String aliasedName) =>
    i1.GeneratedColumn<String>('target_type', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_82(String aliasedName) =>
    i1.GeneratedColumn<String>('target_client_id', aliasedName, false,
        type: i1.DriftSqlType.string);

class Shape16 extends i0.VersionedTable {
  Shape16({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get clientId =>
      columnsByName['client_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get rev =>
      columnsByName['rev']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get lastSyncedAt =>
      columnsByName['last_synced_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get budgetClientId =>
      columnsByName['budget_client_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get periodStart =>
      columnsByName['period_start']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get periodEnd =>
      columnsByName['period_end']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<double> get netSpent =>
      columnsByName['net_spent']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get rolloverIn =>
      columnsByName['rollover_in']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get rolloverOut =>
      columnsByName['rollover_out']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<DateTime> get closedAt =>
      columnsByName['closed_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<DateTime> _column_83(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('period_start', aliasedName, false,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<DateTime> _column_84(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('period_end', aliasedName, false,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<double> _column_85(String aliasedName) =>
    i1.GeneratedColumn<double>('net_spent', aliasedName, false,
        type: i1.DriftSqlType.double,
        defaultValue: const CustomExpression('0.0'));
i1.GeneratedColumn<double> _column_86(String aliasedName) =>
    i1.GeneratedColumn<double>('rollover_in', aliasedName, false,
        type: i1.DriftSqlType.double,
        defaultValue: const CustomExpression('0.0'));
i1.GeneratedColumn<double> _column_87(String aliasedName) =>
    i1.GeneratedColumn<double>('rollover_out', aliasedName, false,
        type: i1.DriftSqlType.double,
        defaultValue: const CustomExpression('0.0'));
i1.GeneratedColumn<DateTime> _column_88(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('closed_at', aliasedName, true,
        type: i1.DriftSqlType.dateTime);

final class Schema6 extends i0.VersionedSchema {
  Schema6({required super.database}) : super(version: 6);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    wallets,
    parties,
    groups,
    transactions,
    categories,
    configs,
    users,
    localChanges,
    syncMetadata,
    categorizables,
    notifications,
    mediaFiles,
    transfers,
    budgets,
    budgetTargets,
    budgetPeriodStates,
    holdings,
    financialPositionCache,
  ];
  late final Shape0 wallets = Shape0(
      source: i0.VersionedTable(
        entityName: 'wallets',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_8,
          _column_9,
          _column_10,
          _column_11,
          _column_12,
          _column_13,
          _column_14,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 parties = Shape1(
      source: i0.VersionedTable(
        entityName: 'parties',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_8,
          _column_12,
          _column_14,
          _column_15,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape2 groups = Shape2(
      source: i0.VersionedTable(
        entityName: 'groups',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_8,
          _column_12,
          _column_14,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape17 transactions = Shape17(
      source: i0.VersionedTable(
        entityName: 'transactions',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_16,
          _column_9,
          _column_89,
          _column_12,
          _column_17,
          _column_18,
          _column_19,
          _column_20,
          _column_21,
          _column_22,
          _column_23,
          _column_59,
          _column_60,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape4 categories = Shape4(
      source: i0.VersionedTable(
        entityName: 'categories',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_24,
          _column_25,
          _column_12,
          _column_9,
          _column_14,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape5 configs = Shape5(
      source: i0.VersionedTable(
        entityName: 'configs',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_26,
          _column_9,
          _column_27,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape6 users = Shape6(
      source: i0.VersionedTable(
        entityName: 'users',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_28,
          _column_29,
          _column_30,
          _column_31,
          _column_32,
          _column_33,
          _column_34,
          _column_35,
          _column_36,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape7 localChanges = Shape7(
      source: i0.VersionedTable(
        entityName: 'local_changes',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(entity_id, entity_type)',
        ],
        columns: [
          _column_37,
          _column_38,
          _column_39,
          _column_40,
          _column_41,
          _column_42,
          _column_43,
          _column_44,
          _column_45,
          _column_46,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape8 syncMetadata = Shape8(
      source: i0.VersionedTable(
        entityName: 'sync_metadata',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(entity_type)',
        ],
        columns: [
          _column_37,
          _column_7,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape9 categorizables = Shape9(
      source: i0.VersionedTable(
        entityName: 'categorizables',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(categorizable_id, categorizable_type, category_client_id)',
        ],
        columns: [
          _column_47,
          _column_48,
          _column_49,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape10 notifications = Shape10(
      source: i0.VersionedTable(
        entityName: 'notifications',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_9,
          _column_50,
          _column_51,
          _column_41,
          _column_52,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape11 mediaFiles = Shape11(
      source: i0.VersionedTable(
        entityName: 'media_files',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(path)',
        ],
        columns: [
          _column_53,
          _column_54,
          _column_15,
          _column_55,
          _column_56,
          _column_57,
          _column_58,
          _column_35,
          _column_36,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape13 transfers = Shape13(
      source: i0.VersionedTable(
        entityName: 'transfers',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_16,
          _column_61,
          _column_62,
          _column_63,
          _column_64,
          _column_65,
          _column_66,
          _column_67,
          _column_68,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape14 budgets = Shape14(
      source: i0.VersionedTable(
        entityName: 'budgets',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_8,
          _column_25,
          _column_12,
          _column_69,
          _column_11,
          _column_70,
          _column_71,
          _column_72,
          _column_73,
          _column_74,
          _column_75,
          _column_76,
          _column_77,
          _column_78,
          _column_79,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape15 budgetTargets = Shape15(
      source: i0.VersionedTable(
        entityName: 'budget_targets',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(budget_client_id, target_type, target_client_id)',
        ],
        columns: [
          _column_80,
          _column_81,
          _column_82,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape16 budgetPeriodStates = Shape16(
      source: i0.VersionedTable(
        entityName: 'budget_period_states',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(client_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_80,
          _column_83,
          _column_84,
          _column_85,
          _column_86,
          _column_87,
          _column_88,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape18 holdings = Shape18(
      source: i0.VersionedTable(
        entityName: 'holdings',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_28,
          _column_8,
          _column_90,
          _column_91,
          _column_11,
          _column_92,
          _column_93,
          _column_94,
          _column_95,
          _column_96,
          _column_97,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape19 financialPositionCache = Shape19(
      source: i0.VersionedTable(
        entityName: 'financial_position_cache',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(cache_key)',
        ],
        columns: [
          _column_98,
          _column_99,
          _column_100,
          _column_101,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

class Shape17 extends i0.VersionedTable {
  Shape17({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get clientId =>
      columnsByName['client_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get rev =>
      columnsByName['rev']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get lastSyncedAt =>
      columnsByName['last_synced_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<double> get amount =>
      columnsByName['amount']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get intent =>
      columnsByName['intent']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get datetime =>
      columnsByName['datetime']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<int> get partyId =>
      columnsByName['party_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get walletId =>
      columnsByName['wallet_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get groupId =>
      columnsByName['group_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get walletClientId =>
      columnsByName['wallet_client_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get partyClientId =>
      columnsByName['party_client_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get groupClientId =>
      columnsByName['group_client_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get transferId =>
      columnsByName['transfer_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get transferClientId =>
      columnsByName['transfer_client_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_89(String aliasedName) =>
    i1.GeneratedColumn<String>('intent', aliasedName, false,
        type: i1.DriftSqlType.string,
        defaultValue: const CustomExpression('\'regular\''));

class Shape18 extends i0.VersionedTable {
  Shape18({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get symbol =>
      columnsByName['symbol']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get quantity =>
      columnsByName['quantity']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get currency =>
      columnsByName['currency']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get unitPrice =>
      columnsByName['unit_price']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get value =>
      columnsByName['value']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get priceSource =>
      columnsByName['price_source']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get provider =>
      columnsByName['provider']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get externalRef =>
      columnsByName['external_ref']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get lastPricedAt =>
      columnsByName['last_priced_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_90(String aliasedName) =>
    i1.GeneratedColumn<String>('symbol', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<double> _column_91(String aliasedName) =>
    i1.GeneratedColumn<double>('quantity', aliasedName, false,
        type: i1.DriftSqlType.double,
        defaultValue: const CustomExpression('0.0'));
i1.GeneratedColumn<double> _column_92(String aliasedName) =>
    i1.GeneratedColumn<double>('unit_price', aliasedName, false,
        type: i1.DriftSqlType.double,
        defaultValue: const CustomExpression('0.0'));
i1.GeneratedColumn<double> _column_93(String aliasedName) =>
    i1.GeneratedColumn<double>('value', aliasedName, false,
        type: i1.DriftSqlType.double,
        defaultValue: const CustomExpression('0.0'));
i1.GeneratedColumn<String> _column_94(String aliasedName) =>
    i1.GeneratedColumn<String>('price_source', aliasedName, false,
        type: i1.DriftSqlType.string,
        defaultValue: const CustomExpression('\'manual\''));
i1.GeneratedColumn<String> _column_95(String aliasedName) =>
    i1.GeneratedColumn<String>('provider', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_96(String aliasedName) =>
    i1.GeneratedColumn<String>('external_ref', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<DateTime> _column_97(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('last_priced_at', aliasedName, true,
        type: i1.DriftSqlType.dateTime);

class Shape19 extends i0.VersionedTable {
  Shape19({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get cacheKey =>
      columnsByName['cache_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get payload =>
      columnsByName['payload']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get currency =>
      columnsByName['currency']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get fetchedAt =>
      columnsByName['fetched_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_98(String aliasedName) =>
    i1.GeneratedColumn<String>('cache_key', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_99(String aliasedName) =>
    i1.GeneratedColumn<String>('payload', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_100(String aliasedName) =>
    i1.GeneratedColumn<String>('currency', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<DateTime> _column_101(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('fetched_at', aliasedName, false,
        type: i1.DriftSqlType.dateTime);
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      case 5:
        final schema = Schema6(database: database);
        final migrator = i1.Migrator(database, schema);
        await from5To6(migrator, schema);
        return 6;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
}) =>
    i0.VersionedSchema.stepByStepHelper(
        step: migrationSteps(
      from1To2: from1To2,
      from2To3: from2To3,
      from3To4: from3To4,
      from4To5: from4To5,
      from5To6: from5To6,
    ));
