// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_development.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB49ck6qT_7LWi6U1NI27RNVRl3ejiYj9Y',
    appId: '1:212694832657:android:ef32b90e0fecc0bb5743b0',
    messagingSenderId: '212694832657',
    projectId: 'trakli',
    storageBucket: 'trakli.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9K-5luMrbIIcO0jUKe7v3VDTI_qHI8TU',
    appId: '1:212694832657:ios:64c09c09fa0f0d485743b0',
    messagingSenderId: '212694832657',
    projectId: 'trakli',
    storageBucket: 'trakli.firebasestorage.app',
    androidClientId:
        '212694832657-0fefkea4n012n38qaoq9siakisdp1m9p.apps.googleusercontent.com',
    iosClientId:
        '212694832657-7er649jbpdlgocs40rntsf7f7i897gc5.apps.googleusercontent.com',
    iosBundleId: 'com.whilesmart.trakli.dev',
  );
}
