name: Android Release (Main + Manual)

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      track:
        description: 'Release track'
        required: true
        default: 'firebase'
        type: choice
        options:
          - firebase
          - playstore

jobs:
  build-and-release:
    name: Android Release Pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.9"
          channel: 'stable'
          cache: true

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          working-directory: android/fastlane

      - name: Install Fastlane gems
        working-directory: android/fastlane
        run: bundle install

      - name: Setup Service Accounts
        env:
          GOOGLE_SERVICES_ACCOUNT_BASE64: ${{ secrets.GOOGLE_SERVICES_ACCOUNT_BASE64 }}
          CREDENTIAL_FILE_CONTENT: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        run: |
          printf '%s' "$GOOGLE_SERVICES_ACCOUNT_BASE64" | base64 --decode > google_service_account.json
          printf '%s' "$CREDENTIAL_FILE_CONTENT" > service_credentials_content.json

      - name: Setup Android signing keystore
        run: |
          printf '%s' "${{ secrets.ANDROID_KEYSTORE_FILE_BASE64 }}" | base64 --decode > android/key.jks

      - name: Setup Android key.properties
        run: |
          cat <<EOF > android/key.properties
          storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyAlias=release
          storeFile=../key.jks
          EOF

      - name: Release to Firebase
        if: ${{ github.event_name == 'push' || github.event.inputs.track == 'firebase' }}
        working-directory: android/fastlane
        run: bundle exec fastlane release_play_store_using_firebase
        env:
          APP_PACKAGE_NAME: ${{ vars.APP_PACKAGE_NAME }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}

      - name: Release to Play Store
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.track == 'playstore' }}
        working-directory: android/fastlane
        run: bundle exec fastlane release_play_store
        env:
          APP_PACKAGE_NAME: ${{ vars.APP_PACKAGE_NAME }}
