name: iOS Certificate Setup

on:
  workflow_dispatch:

jobs:
  setup-certificates:
    runs-on: macos-latest
    steps:


#  diff "${PODS_PODFILE_DIR_PATH}/Podfile.lock" "${PODS_ROOT}/Manifest.lock" > /dev/null
